#!/usr/bin/osascript

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Clear Notifications
# @raycast.mode silent
# 
# Optional parameters:
# @raycast.icon 🤖

tell application "System Events"
  try
    set _groups to groups of UI element 1 of scroll area 1 of group 1 of window "Notification Center" of application process "NotificationCenter"
    
    repeat with _group in _groups
      
      set _actions to actions of _group
      
      repeat with _action in _actions
        if description of _action is in {"Close", "Clear All"} then
          perform _action
          
        end if
      end repeat
      
    end repeat
    
  end try
  
  set processName to "Microsoft Outlook"
  set matchedProcess to first process whose name is processName
  
  try
    repeat with theWindow in (every window of matchedProcess)
      set windowName to name of theWindow
      if windowName contains "Reminder" then
        repeat with btn in buttons of theWindow
          if description of btn is "close button" then
            click btn
            exit repeat
          end if
        end repeat
      end if
    end repeat
  end try
end tell

