[default_session]
startup_command = "~/.dotfiles/scripts/panes.sh"

[[session]]
name = "nvim_plugins"
path = "~/.dotfiles/nvim/lua"
startup_command = "nvim plugins.lua"

[[session]]
name = "obsidian_egradman"
path = "~/Documents/egradman/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "obsidian_red6"
path = "~/Documents/red6/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "obsidian_shared"
path = "~/Documents/shared/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "lcs"
startup_command = '/run/current-system/sw/bin/kitten ssh -A  -t rkschaider@192.168.5.40 '

[[session]]
name = "dmz"
startup_command = '$HOME/.dotfiles/scripts/setup_ssh_pane.sh egradman@dmz.gradman.com'
