- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: packages
      become: true
      dnf:
        name:
          - unzip
          - wget
          - ripgrep
          - tmux
          - git
          - lnav
          - gettext
          - zsh
    - name: download direnv
      get_url:
          url: https://github.com/direnv/direnv/releases/download/v2.34.0/direnv.linux-amd64
          dest: ~/.dotfiles/bin/direnv
          mode: "744"
    - name: download neovim
      unarchive:
          remote_src: yes
          src: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
          dest: ~/.dotfiles/
          mode: "744"
    - name: link nvim
      file:
          dest: ~/.dotfiles/bin/nvim
          src: ~/.dotfiles/nvim-linux64/bin/nvim
          state: link

    - name: download bat
      unarchive:
          remote_src: yes
          src: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-x86_64-unknown-linux-gnu.tar.gz
          dest: ~/.dotfiles/
          mode: "744"
    - name: link bat
      file:
          dest: ~/.dotfiles/bin/bat
          src: ~/.dotfiles/bat-v0.24.0-x86_64-unknown-linux-gnu/bat
          state: link
