- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install some brews
      community.general.homebrew:
        name:
          - neovim
          - cmake
          - ripgrep
          - tmux
          - git
          - lnav
          - bat
          - gettext
          - direnv
          - node
          - universal-ctags
          - entr

    - name: Install some casks
      community.general.homebrew:
        name:
          - homebrew/cask/vagrant
          - homebrew/cask/obsidian
          - homebrew/cask/launchbar
          - homebrew/cask/moom
          - homebrew/cask/rhino8
          - homebrew/cask/teams
          - homebrew/cask/outlook
          - homebrew/cask/iterm2
          - homebrew/cask/kicad
          - homebrew/cask/karabiner-elements
-
        state: present

