- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install some brews
      community.general.homebrew:
        name:
          - neovim
          - ripgrep
          - tmux
          - git
          - lnav
          - bat
          - gettext
          - direnv
          - node
          - universal-ctags
          - entr

    - name: Install some casks
      community.general.homebrew:
        name:
          - homebrew/cask/vagrant
          - homebrew/cask/obsidian
          - homebrew/cask/launchbar
          - homebrew/cask/moom
          - homebrew/cask/microsoft-teams
          - homebrew/cask/microsoft-outlook
          - homebrew/cask/iterm2
          - homebrew/cask/kicad
          - homebrew/cask/karabiner-elements
          - homebrew/cask/keyboard-maestro
          - homebrew/cask/google-chrome
        state: present

