- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: packages
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - fzf
          - ripgrep
          - tmux
          - git
          - lnav
          - bat
          - gettext
          - zsh

    - name: download neovim
      unarchive:
        remote_src: yes
        src: https://github.com/neovim/neovim/archive/refs/tags/stable.tar.gz
        dest: /tmp
    - name: build neovim
      command:
        chdir: /tmp/neovim-stable
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/.dotfiles/neovim
    - name: install neovim
      command:
        chdir: /tmp/neovim-stable
        cmd: make install
    - name: link neovim
      file:
        src: ~/.dotfiles/neovim/bin/nvim
        dest: ~/.dotfiles/bin/nvim
        state: link

